id: P8FB5AA41
initial_creation_type: input
source_metadata:
  title: Averting Obstacles
  language: bo
  description: 'A series of apotropaic practices and rites for averting obstacles
    and dispelling negativity:'
  volume:
    a64bfbcd6c2447cf9159a9388de737a0:
      title: The Ultimate, Natural Dispeller of Obstacles
      parent: General
    63b69a3f95434baba751e543e99f6fa1:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    a73b2a23a2004f3e90b461311a1de20a:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Other
    10c8dd6db3164fae8e0ac0af43cf962a:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Other
    93db3256c6ef425e9fe2d9a107cc556b:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Repelling Invasion
    8a471a3655114be6a8200d65d751e7be:
      title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
      parent: Repelling Invasion
    751aa5602d974228bf2c7001219ae913:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    8b8174b993ea4219ac9a7f3514a080fe:
      title: Averting Obstacles through Sitātapatrā
      parent: Sitātapatrā
    f094771b24884560b0e24953c123f60c:
      title: A Short Practice for Averting Obstacles through Vajrakīla
      parent: Vajrakīla
created_at: '2022-03-01T02:55:09.616361'
last_modified_at: '2022-03-01T02:55:09.616364'
